name: build and push to dockerhub

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  jib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: v
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            echo "val=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
          else
            echo "val=0.0.1-$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8

      - name: Build and push
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: gradle -Pversion=${{ steps.v.outputs.val }} clean test jib
